# starship configuration

[status]
disabled = false

[git_commit]
commit_hash_length = 8
format = "[$hash]($style) "
only_detached = false

[python]
symbol = "ğŸ‰ "

[cmd_duration]
style = "dimmed bold yellow"

