# starship configuration

[status]
disabled = false
pipestatus = true
symbol = ''

[git_commit]
commit_hash_length = 12
format = "[$hash]($style) "
only_detached = false

[python]
symbol = "ğŸ‰ "

[cmd_duration]
style = "dimmed bold yellow"

